name: hexalyte_ams
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  shared_preferences: ^2.3.3
  fl_chart: ^0.64.0
  syncfusion_flutter_pdf: ^28.1.39
  path_provider: ^2.1.5
  open_file: ^3.5.10
  dio: ^5.7.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^4.0.1
  image_picker: ^1.1.2
  image_cropper: ^8.0.1
  get: ^4.7.2
  iconsax: ^0.0.8
  lottie: ^3.3.1
  animate_do: ^4.1.1
  pdf: ^3.11.3
  cached_network_image: ^3.4.1
  logger: ^2.5.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  lucide_icons: ^0.257.0
  percent_indicator: ^4.2.3
  syncfusion_flutter_core: ^28.1.39
  syncfusion_flutter_charts: ^28.1.39
  intl: ^0.20.2
  url_launcher: ^6.1.14
  webview_flutter: ^4.2.2
  permission_handler: ^11.1.0
  flutter_tawkto: ^0.0.5
  flutter_inappwebview: ^6.0.0
  provider: ^6.0.5
  google_fonts: ^6.1.0
  printing: ^5.14.2
  share_plus: ^10.1.4

permission_handler: ^10.0.0  # Or the latest version





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"



flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/logo22.png
    - assets/images/app_icon.png
    - assets/images/logo3.png
    - assets/images/help-and-support.png
    - assets/images/support-ticket.png
    - assets/images/car.webp
    - assets/images/land.jpg
    - assets/images/building.jpg
    - assets/images/1.webp
    - assets/images/2.webp
    - assets/images/3.webp
    - assets/images/login.png
    - assets/images/logo36.png
    - assets/images/loading.json


